services:
  ros-iface-streaming:
    image: ros-iface-streaming
    container_name: ros-iface-streaming
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

